# Generated by Django 4.1.7 on 2023-03-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novosti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актеры и РежисерыНов', 'verbose_name_plural': 'Актеры и РежисерыНов'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'КатегорииНов', 'verbose_name_plural': 'КатегорииНов'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'ЖанрНов', 'verbose_name_plural': 'ЖанрыНов'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'ФильмНов', 'verbose_name_plural': 'ФильмыНов'},
        ),
        migrations.AlterModelOptions(
            name='movieshots',
            options={'verbose_name': 'Кадр из ФильмаНов', 'verbose_name_plural': 'Кадры из ФильмаНов'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='film_actornews', to='novosti.actor', verbose_name='актеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='film_directornews', to='novosti.actor', verbose_name='режиссер'),
        ),
    ]
