# Generated by Django 4.1.7 on 2023-03-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novosti', '0002_alter_actor_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actor',
            new_name='Actor2',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Category2',
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='Genre2',
        ),
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movie2',
        ),
        migrations.RenameModel(
            old_name='MovieShots',
            new_name='MovieShots2',
        ),
    ]
