# Generated by Django 4.1.7 on 2023-03-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='ame',
            new_name='name',
        ),
    ]
